# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  #before_all do
  #  cocoapods
  #end

  desc "Build App for Debug"
  lane :debug_build do
    #enable_automatic_code_signing
    build_ios_app(configuration: "Debug", export_method: "development")
  end

  desc "[WIP] Build App for AdHoc"
  lane :adhoc do
    build_ios_app(configuration: "Distribution_AdHoc", export_method: "ad-hoc")
  end

  desc "[WIP] Build App for Release"
  lane :build do
    build_ios_app
  end

  desc "Runs all the tests"
  lane :test do
    scan
    #snapshot
  end


  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
